/*
 * File: app/view/MyForm.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform',

    requires: [
        'MyApp.view.MyFormViewModel',
        'MyApp.view.MyFormViewController',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    controller: 'myform',
    viewModel: {
        type: 'myform'
    },
    height: 600,
    width: 900,
    layout: 'form',
    bodyPadding: 10,
    title: 'Employee Form',
    margin: '-620 20 -620 20',

    items: [
       /* {
            xtype: 'textfield',
            id: 'id',
            fieldLabel: 'Id'
        }, */
        {
            xtype: 'textfield',
            id: 'name',
            fieldLabel: 'Name'
        },
        {
            xtype: 'textfield',
            id: 'lastname',
            fieldLabel: 'Last Name'
        },
        {
            xtype: 'radiogroup',
            id: 'radiogroup',
            fieldLabel: 'Condition',
            items: [
                {
                    xtype: 'radiofield',
                    id: 'radioActive',
                    boxLabel: 'Active'
                },
                {
                    xtype: 'radiofield',
                    id: 'radioPassive',
                    boxLabel: 'Passive'
                }
            ]
        },
        {
            xtype: 'button',
            id: 'submitButton',
            text: 'Submit',
            listeners: {
                click: 'onButtonClick'
            }
        },
        {
          xtype: 'button',
          id: 'DeleteButton',
            margin: '-32 80 -32 80',
          text: 'DeleteAll',
          listeners: {
              click: 'onDeleteButtonClick'
          }
        },


    ]

});