/*
 * File: app/view/MyFormViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyFormViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.myform',



    /*
    listeners: {
                        click: 'onDeleteSelectedButtonClick',
                            scope: this,
                            fn: function (sm, selection) {
                                var selection = this.getView().getSelectionModel().getSelection()[0]
                                /*if (selection.length > 1) {
                                    store.removeAll(selection);
                                }*/ //This not working
                               // else
                                 //   store.remove(selection);
                                   // store.sync();
                               // }
                           // }




});